### ISSUE TITLE
How much will students know going in?

### ISSUE THREAD

**Issue by jonahweissman** [chssigma/git-lessons#1]
Lesson 2 seems to be [introducing students to bash](https://github.com/chssigma/git-lessons/blob/master/2_Learn_about_repositories.md#using-terminal). I thought I remembered Dr. Shields already having a lesson on that for Engineering 3 students.

I have two questions:
- At what engineering level will students take this module?
- What modules will they have already taken when they start?

**Comment by Tim-Jackins** [comment]
I don't have a good issue template but if could itemize your questions I think that would be helpful.
ie:
1. At what engineering level will students take this module?
2. What modules will they have already taken when they start?

Don't students wait to learn about terminals till they start using raspberry pis in engineering 4? Shields can chime in here.
1. Currently, engineering 4 and 5 students will be learning how to use Git.
2. Only 2-3 pages of Git will go into the engineering 4 curriculum. Most of the lessons will be removed or made smaller when it goes into the engineering curriculum. The curriculum is already long so Shields just wants students to have a basic understanding of Git and know that it's an option.

Git-lessons is going to primarily act as a resource for students who decide to use Git for their projects and want a more detailed tutorial. I also want to have it be an option for CS classes as well.

**Comment by jonahweissman** [comment]
Thanks for the info! I have a few more thoughts.

> Don't students wait to learn about terminals till they start using raspberry pis in engineering 4?

You're right; I got 'em switched up in my head.

> Only 2-3 pages of Git will go into the engineering 4 curriculum. Most of the lessons will be removed or made smaller when it goes into the engineering curriculum. The curriculum is already long so Shields just wants students to have a basic understanding of Git and know that it's an option.
>
> Git-lessons is going to primarily act as a resource for students who decide to use Git for their projects and want a more detailed tutorial. I also want to have it be an option for CS classes as well.

So you really have two tasks here, (1) present Git in such a manner that people can see if it would be useful for them and (2) teach them how to use Git. It might be easier to address these separately.

There's a lot of ways to go about it, but inspiring people to use Git is probably best done by presenting specific situations that Git makes life easier. You can give them a fun CHS engineering / computer science vibe by referencing things students will be familiar with, e.g. show them a picture of someone's share file folder with "thing.sldprt", "thing_v2.sldprt", "thing_v2_revised.sldprt".

To the second point, tutorials on using Git and GitHub [already exist](https://try.github.io/), no need to reinvent the wheel. You might want to include introductory material if any of those tutorials assume lots of prior knowledge, but all-in-all the Sigma lab's Git needs are not so unique as to require a specialized tutorial. You have some good material in this repo, but it might be worthwhile to take a step back and evaluate the most effective ways to educate people about Git.

**Comment by Tim-Jackins** [comment]
>You can give them a fun CHS engineering / computer science vibe by referencing things students will be familiar with

This is a fantastic idea that I'll incorporate when I do the quicker / simpler pages.

>To the second point, tutorials on using Git and GitHub already exist, no need to reinvent the wheel.

I totally agree I'm using online tutorials to piece together Git-lessons. I'm only adjusting a few so that they are easier to grade. The only thing that will really be sigma specific will be the README which will be informed by the current EOY pdf rubric and Richard's standard.

**Comment by jonahweissman** [comment]
>  I'm only adjusting a few so that they are easier to grade.

From the lessons I've looked at, it seems way more micro-manage-y than I would expect for Engineering 4/5. Doesn't "git-it" automatically grade your completion of tasks?

**Comment by Tim-Jackins** [comment]
Yes but they would be doing the lessons on raspberry pis

**Comment by Tim-Jackins** [comment]
This may be more of a collection of info to then be put into an engineering format.

**Comment by Tim-Jackins** [comment]
This has been very helpful I'll revise when I get to work on Friday. Thanks @jonahweissman !

**Comment by Tim-Jackins** [comment]
This has been very helpful I'll revise when I get to work on Friday. Thanks @jonahweissman !
