### ISSUE TITLE
School email or personal?

### ISSUE THREAD

**Issue by jonahweissman** [chssigma/git-lessons#3]
If I'm an engineering student and I see this:

>Set your email:
>```
>git config --global user.email "youremail@example.com"
>```

I'm immediately going to ask whether I should use my @charlottesvilleschools.org address or my personal address. Which would be more appropriate? 

### To do
- [x] figure out whether students should use school or personal email when configuring git
- [ ] add this guidance to tutorial

**Comment by Tim-Jackins** [comment]
I would say personal. Both because their emails will be disabled in 1-2 years and because I would want them to use a personal email for signing up for GitHub. But this seems like a Shields / school rule thing.

**Comment by jonahweissman** [comment]
I'm inclined to agree. However, note that people can later add their personal email and make it their primary email in [settings](https://github.com/settings/emails), so it wouldn't be disastrous if students had to use their school email at first.

**Comment by Tim-Jackins** [comment]
Interesting, what will probably happen is students will be able to pick whatever email they want and we'll advise them to use their GitHub email.

**Comment by jonahweissman** [comment]
> we'll advise them to use their GitHub email.

would that be school or personal?

**Comment by Tim-Jackins** [comment]
I just talked to Shields, kids will be using their school email unless they already have an account.
