### ISSUE TITLE
Integrating Git tutorial into another lesson/project

### ISSUE THREAD

**Issue by jonahweissman** [chssigma/git-lessons#4]
Making a repo called `hello-world` with some garbage text file is nice and all, but it might help people more if they were setting up a git repo for something they actually would use. Maybe this could be rolled into "Hello Python" or something like that? It might make it feel more tangible, and they might be more likely to keep using Git.

**Comment by Tim-Jackins** [comment]
There's currently no instruction in the rest of the curriculum about how to store your project. I'll run this by shields tomorrow.

**Comment by Tim-Jackins** [comment]
Students are going to have to put their base engineering stuff into Git anyways. I'm going to keep the hello world tutorial.
