### ISSUE TITLE
Mention in README how this repo will be used

### ISSUE THREAD

**Issue by jonahweissman** [chssigma/git-lessons#6]
In #2, @Tim-Jackins, [you mentioned](https://github.com/chssigma/git-lessons/pull/2#issuecomment-410478270) how the contents of this repo would be copied into canvas, rather than consumed on GitHub. It might be helpful to mention this in the README, as well as how frequently you'll update canvas to reflect changes here. Not super critical, but might be helpful if students have feedback after taking the lesson or they stumble across this repo at https://github.com/chssigma.

**Comment by Tim-Jackins** [comment]
Very true. I have some iSTEM stuff to tend to but later today I'll add that.
